// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liztzvnwvwgjjqrteiep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpenR6dm53dndnampxcnRlaWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDY2MzUsImV4cCI6MjA2OTQ4MjYzNX0.2bo4u3yeMAyJ7Dz-WQYyjrGFPLSwyai865ELpfRJjwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});