// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snglslmydxlfenfgrgsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZ2xzbG15ZHhsZmVuZmdyZ3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjI0NjgsImV4cCI6MjA3MjQ5ODQ2OH0.DGx6kpEBvicT0UTZJrCuQ1X0Glvv0EjK_r0GzUqSmbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});